/*
 * @file engine/src/config/registry/EntriesInitState.cpp
 * @author Luis1454
 * @project BLITZAR
 * @brief Responsibility-focused simulation option definitions.
 */

#include "Internal.hpp"

#include "config/core/Config.hpp"

#include <cstddef>

namespace bltzr_config {

extern const SimulationOptionEntry kInitStateOptions[] = {
    {SimulationOptionGroup::InitState, OptionKind::String, "--init-mode", "", "init_mode", "", "",
     "  --init-mode "
     "<disk_orbit|galaxy|galaxy_collision|cosmology|random_cloud|cube_random|sphere_random|two_"
     "body|three_body|"
     "plummer_sphere|binary_star|solar_system|sph_collapse|file>"
     "\n",
     "", offsetof(SimulationConfig, initMode), 0.0, 0.0, false, false},
    {SimulationOptionGroup::InitState, OptionKind::Uint, "--init-seed", "", "init_seed", "", "",
     "  --init-seed <n>\n", "", offsetof(SimulationConfig, initSeed), 0.0, 0.0, false, false},
    {SimulationOptionGroup::InitState, OptionKind::Bool, "--init-include-central-body", "",
     "init_include_central_body", "", "", "  --init-include-central-body <true|false>\n", "",
     offsetof(SimulationConfig, initIncludeCentralBody), 0.0, 0.0, false, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-central-mass", "",
     "init_central_mass", "", "", "  --init-central-mass <float>\n", "",
     offsetof(SimulationConfig, initCentralMass), 0.000001, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-central-x", "", "init_central_x",
     "", "", "  --init-central-x <float>\n", "", offsetof(SimulationConfig, initCentralX), 0.0, 0.0,
     false, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-central-y", "", "init_central_y",
     "", "", "  --init-central-y <float>\n", "", offsetof(SimulationConfig, initCentralY), 0.0, 0.0,
     false, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-central-z", "", "init_central_z",
     "", "", "  --init-central-z <float>\n", "", offsetof(SimulationConfig, initCentralZ), 0.0, 0.0,
     false, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-central-vx", "",
     "init_central_vx", "", "", "  --init-central-vx <float>\n", "",
     offsetof(SimulationConfig, initCentralVx), 0.0, 0.0, false, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-central-vy", "",
     "init_central_vy", "", "", "  --init-central-vy <float>\n", "",
     offsetof(SimulationConfig, initCentralVy), 0.0, 0.0, false, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-central-vz", "",
     "init_central_vz", "", "", "  --init-central-vz <float>\n", "",
     offsetof(SimulationConfig, initCentralVz), 0.0, 0.0, false, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-disk-mass", "", "init_disk_mass",
     "", "", "  --init-disk-mass <float>\n", "", offsetof(SimulationConfig, initDiskMass), 0.000001,
     0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-disk-radius-min", "",
     "init_disk_radius_min", "", "", "  --init-disk-radius-min <float>\n", "",
     offsetof(SimulationConfig, initDiskRadiusMin), 0.000001, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-disk-radius-max", "",
     "init_disk_radius_max", "", "", "  --init-disk-radius-max <float>\n", "",
     offsetof(SimulationConfig, initDiskRadiusMax), 0.000001, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-disk-thickness", "",
     "init_disk_thickness", "", "", "  --init-disk-thickness <float>\n", "",
     offsetof(SimulationConfig, initDiskThickness), 0.0, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-velocity-scale", "",
     "init_velocity_scale", "", "", "  --init-velocity-scale <float>\n", "",
     offsetof(SimulationConfig, initVelocityScale), 0.0, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-cloud-half-extent", "",
     "init_cloud_half_extent", "", "", "  --init-cloud-half-extent <float>\n", "",
     offsetof(SimulationConfig, initCloudHalfExtent), 0.000001, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-cube-half-extent", "",
     "init_cube_half_extent", "", "", "  --init-cube-half-extent <float>\n", "",
     offsetof(SimulationConfig, initCubeHalfExtent), 0.000001, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-sphere-radius", "",
     "init_sphere_radius", "", "", "  --init-sphere-radius <float>\n", "",
     offsetof(SimulationConfig, initSphereRadius), 0.000001, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-cloud-speed", "",
     "init_cloud_speed", "", "", "  --init-cloud-speed <float>\n", "",
     offsetof(SimulationConfig, initCloudSpeed), 0.0, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-particle-mass", "",
     "init_particle_mass", "", "", "  --init-particle-mass <float>\n", "",
     offsetof(SimulationConfig, initParticleMass), 0.000000000001, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Bool, "--cosmology-enabled", "",
     "cosmology_enabled", "", "", "  --cosmology-enabled <true|false>\n", "",
     offsetof(SimulationConfig, cosmologyEnabled), 0.0, 0.0, false, false},
    {SimulationOptionGroup::InitState, OptionKind::String, "--cosmology-mode", "", "cosmology_mode",
     "", "", "  --cosmology-mode <expanding_preview|comoving>\n", "",
     offsetof(SimulationConfig, cosmologyMode), 0.0, 0.0, false, false},
    {SimulationOptionGroup::InitState, OptionKind::String, "--cosmology-geometry", "",
     "cosmology_geometry", "", "", "  --cosmology-geometry <sphere|cube>\n", "",
     offsetof(SimulationConfig, cosmologyGeometry), 0.0, 0.0, false, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--cosmology-box-half-extent", "",
     "cosmology_box_half_extent", "", "", "  --cosmology-box-half-extent <float>\n", "",
     offsetof(SimulationConfig, cosmologyBoxHalfExtent), 0.000001, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--cosmology-sphere-radius", "",
     "cosmology_sphere_radius", "", "", "  --cosmology-sphere-radius <float>\n", "",
     offsetof(SimulationConfig, cosmologySphereRadius), 0.000001, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--cosmology-h0", "", "cosmology_h0", "",
     "", "  --cosmology-h0 <float>\n", "", offsetof(SimulationConfig, cosmologyHubbleH0), 0.0, 0.0,
     true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--cosmology-omega-m", "",
     "cosmology_omega_m", "", "", "  --cosmology-omega-m <float>\n", "",
     offsetof(SimulationConfig, cosmologyOmegaMatter), 0.0, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--cosmology-omega-lambda", "",
     "cosmology_omega_lambda", "", "", "  --cosmology-omega-lambda <float>\n", "",
     offsetof(SimulationConfig, cosmologyOmegaLambda), 0.0, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--cosmology-omega-radiation", "",
     "cosmology_omega_radiation", "", "", "  --cosmology-omega-radiation <float>\n", "",
     offsetof(SimulationConfig, cosmologyOmegaRadiation), 0.0, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--cosmology-initial-scale-factor", "",
     "cosmology_initial_scale_factor", "", "", "  --cosmology-initial-scale-factor <float>\n", "",
     offsetof(SimulationConfig, cosmologyInitialScaleFactor), 0.000001, 1.0e12, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--cosmology-perturbation", "",
     "cosmology_perturbation_amplitude", "", "", "  --cosmology-perturbation <float>\n", "",
     offsetof(SimulationConfig, cosmologyPerturbationAmplitude), 0.0, 1.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--cosmology-peculiar-velocity", "",
     "cosmology_peculiar_velocity_scale", "", "", "  --cosmology-peculiar-velocity <float>\n", "",
     offsetof(SimulationConfig, cosmologyPeculiarVelocityScale), 0.0, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::String, "--cosmology-mass-model", "",
     "cosmology_mass_model", "", "",
     "  --cosmology-mass-model <critical_density|total_mass|particle_mass>\n", "",
     offsetof(SimulationConfig, cosmologyMassModel), 0.0, 0.0, false, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--cosmology-total-mass", "",
     "cosmology_total_mass", "", "", "  --cosmology-total-mass <float>\n", "",
     offsetof(SimulationConfig, cosmologyTotalMass), 0.0, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--scene-offset-x", "", "scene_offset_x",
     "", "", "  --scene-offset-x <float>\n", "", offsetof(SimulationConfig, sceneOffsetX), 0.0, 0.0,
     false, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--scene-offset-y", "", "scene_offset_y",
     "", "", "  --scene-offset-y <float>\n", "", offsetof(SimulationConfig, sceneOffsetY), 0.0, 0.0,
     false, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--scene-offset-z", "", "scene_offset_z",
     "", "", "  --scene-offset-z <float>\n", "", offsetof(SimulationConfig, sceneOffsetZ), 0.0, 0.0,
     false, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--scene-rotation-x", "",
     "scene_rotation_x", "", "", "  --scene-rotation-x <degrees>\n", "",
     offsetof(SimulationConfig, sceneRotationX), -360.0, 360.0, true, true},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--scene-rotation-y", "",
     "scene_rotation_y", "", "", "  --scene-rotation-y <degrees>\n", "",
     offsetof(SimulationConfig, sceneRotationY), -360.0, 360.0, true, true},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--scene-rotation-z", "",
     "scene_rotation_z", "", "", "  --scene-rotation-z <degrees>\n", "",
     offsetof(SimulationConfig, sceneRotationZ), -360.0, 360.0, true, true},
    {SimulationOptionGroup::InitState, OptionKind::String, "--scene-copy-axis", "",
     "scene_copy_axis", "", "", "  --scene-copy-axis <x|y|z>\n", "",
     offsetof(SimulationConfig, sceneCopyAxis), 0.0, 0.0, false, false},
    {SimulationOptionGroup::InitState, OptionKind::Uint, "--scene-rotation-copies", "",
     "scene_rotation_copies", "", "", "  --scene-rotation-copies <1..256>\n", "",
     offsetof(SimulationConfig, sceneRotationCopies), 1.0, 256.0, true, true},
    {SimulationOptionGroup::InitState, OptionKind::Bool, "--scene-mirror-x", "", "scene_mirror_x",
     "", "", "  --scene-mirror-x <true|false>\n", "", offsetof(SimulationConfig, sceneMirrorX), 0.0,
     0.0, false, false},
    {SimulationOptionGroup::InitState, OptionKind::Bool, "--scene-mirror-y", "", "scene_mirror_y",
     "", "", "  --scene-mirror-y <true|false>\n", "", offsetof(SimulationConfig, sceneMirrorY), 0.0,
     0.0, false, false},
    {SimulationOptionGroup::InitState, OptionKind::Bool, "--scene-mirror-z", "", "scene_mirror_z",
     "", "", "  --scene-mirror-z <true|false>\n", "", offsetof(SimulationConfig, sceneMirrorZ), 0.0,
     0.0, false, false},
};

extern const std::size_t kInitStateOptionCount =
    sizeof(kInitStateOptions) / sizeof(kInitStateOptions[0]);

} // namespace bltzr_config
