/*
 * @file engine/src/config/SimulationOptionRegistryEntries.cpp
 * @author Luis1454
 * @project BLITZAR
 * @brief Configuration parsing, validation, and serialization implementation.
 */

#include "Internal.hpp"

#include "config/core/Config.hpp"

#include <cstddef>

namespace bltzr_config {

const SimulationOptionEntry kSimulationOptions[] = {
    {SimulationOptionGroup::Core, OptionKind::Uint, "--particle-count", "", "particle_count", "",
     "BLITZAR_SERVER_PARTICLES", "  --particle-count <n>\n", "",
     offsetof(SimulationConfig, particleCount), 2.0, 0.0, true, false},
    {SimulationOptionGroup::Core, OptionKind::Float, "--dt", "", "dt", "", "", "  --dt <float>\n",
     "", offsetof(SimulationConfig, dt), kMinSimulationDt, 0.0, true, false},
    {SimulationOptionGroup::Core, OptionKind::Solver, "--solver", "", "solver", "", "",
     "  --solver <pairwise_cuda|octree_gpu|octree_cpu|fmm_cpu>\n", "",
     offsetof(SimulationConfig, solver), 0.0, 0.0, false, false},
    {SimulationOptionGroup::Core, OptionKind::Integrator, "--integrator", "", "integrator", "", "",
     "  --integrator <euler|rk4|leapfrog>\n", "", offsetof(SimulationConfig, integrator), 0.0, 0.0,
     false, false},
    {SimulationOptionGroup::Core, OptionKind::PerformanceProfile, "--performance-profile", "",
     "performance_profile", "", "",
     "  --performance-profile <interactive|balanced|quality|custom>\n", "",
     offsetof(SimulationConfig, performanceProfile), 0.0, 0.0, false, false},
    {SimulationOptionGroup::Core, OptionKind::String, "--profile", "", "simulation_profile", "", "",
     "  --profile "
     "<disk_orbit|galaxy_collision|plummer_sphere|binary_star|solar_system|sph_collapse>\n",
     "", offsetof(SimulationConfig, simulationProfile), 0.0, 0.0, false, false},
    {SimulationOptionGroup::Core, OptionKind::Float, "--substep-target-dt", "", "substep_target_dt",
     "", "", "  --substep-target-dt <float|0=auto>\n", "",
     offsetof(SimulationConfig, substepTargetDt), 0.0, 0.0, true, false},
    {SimulationOptionGroup::Core, OptionKind::Uint, "--max-substeps", "", "max_substeps", "", "",
     "  --max-substeps <n>\n", "", offsetof(SimulationConfig, maxSubsteps), 1.0, 1024.0, true,
     true},
    {SimulationOptionGroup::Core, OptionKind::Bool, "--adaptive-time-steps", "",
     "adaptive_time_steps", "", "", "  --adaptive-time-steps <true|false>\n", "",
     offsetof(SimulationConfig, adaptiveTimeStepsEnabled), 0.0, 0.0, false, false},
    {SimulationOptionGroup::Core, OptionKind::Bool, "--adaptive-cost-guard", "",
     "adaptive_cost_guard", "", "", "  --adaptive-cost-guard <true|false>\n", "",
     offsetof(SimulationConfig, adaptiveTimeStepCostGuard), 0.0, 0.0, false, false},
    {SimulationOptionGroup::Core, OptionKind::Uint, "--adaptive-max-level", "",
     "adaptive_max_level", "", "", "  --adaptive-max-level <0..12>\n", "",
     offsetof(SimulationConfig, adaptiveTimeStepMaxLevel), 0.0, 12.0, true, true},
    {SimulationOptionGroup::Core, OptionKind::Float, "--adaptive-eta", "", "adaptive_eta", "", "",
     "  --adaptive-eta <0.01..1>\n", "", offsetof(SimulationConfig, adaptiveTimeStepEta), 0.01, 1.0,
     true, true},
    {SimulationOptionGroup::Core, OptionKind::Uint, "--snapshot-publish-ms", "",
     "snapshot_publish_period_ms", "", "", "  --snapshot-publish-ms <n>\n", "",
     offsetof(SimulationConfig, snapshotPublishPeriodMs), 1.0, 1000.0, true, true},
    {SimulationOptionGroup::Core, OptionKind::Float, "--octree-theta", "", "octree_theta", "", "",
     "  --octree-theta <float>\n", "", offsetof(SimulationConfig, octreeTheta), 0.01, 0.0, true,
     false},
    {SimulationOptionGroup::Core, OptionKind::Float, "--octree-softening", "", "octree_softening",
     "", "", "  --octree-softening <float>\n", "", offsetof(SimulationConfig, octreeSoftening),
     0.000001, 0.0, true, false},
    {SimulationOptionGroup::Core, OptionKind::OctreeCriterion, "--octree-opening-criterion", "",
     "octree_opening_criterion", "", "", "  --octree-opening-criterion <com|bounds>\n", "",
     offsetof(SimulationConfig, octreeOpeningCriterion), 0.0, 0.0, false, false},
    {SimulationOptionGroup::Core, OptionKind::Bool, "--octree-theta-auto-tune", "",
     "octree_theta_auto_tune", "", "", "  --octree-theta-auto-tune <true|false>\n", "",
     offsetof(SimulationConfig, octreeThetaAutoTune), 0.0, 0.0, false, false},
    {SimulationOptionGroup::Core, OptionKind::Float, "--octree-theta-auto-min", "",
     "octree_theta_auto_min", "", "", "  --octree-theta-auto-min <float>\n", "",
     offsetof(SimulationConfig, octreeThetaAutoMin), 0.01, 4.0, true, true},
    {SimulationOptionGroup::Core, OptionKind::Float, "--octree-theta-auto-max", "",
     "octree_theta_auto_max", "", "", "  --octree-theta-auto-max <float>\n", "",
     offsetof(SimulationConfig, octreeThetaAutoMax), 0.01, 4.0, true, true},
    {SimulationOptionGroup::Core, OptionKind::Bool, "--treepm-enabled", "", "treepm_enabled", "",
     "", "  --treepm-enabled <true|false>\n", "", offsetof(SimulationConfig, treePmEnabled), 0.0,
     0.0, false, false},
    {SimulationOptionGroup::Core, OptionKind::TreePmPreset, "--treepm-preset", "", "treepm_preset",
     "", "",
     "  --treepm-preset <pm_only|local_grid_fast|hybrid_balanced|"
     "hybrid_quality|tree_quality|custom>\n",
     "", offsetof(SimulationConfig, treePmPreset), 0.0, 0.0, false, false},
    {SimulationOptionGroup::Core, OptionKind::TreePmModel, "--treepm-model", "", "treepm_model", "",
     "", "  --treepm-model <auto|local_grid|tree|exact_tree|hybrid|pm_only>\n", "",
     offsetof(SimulationConfig, treePmModel), 0.0, 0.0, false, false},
    {SimulationOptionGroup::Core, OptionKind::TreePmLayout, "--treepm-layout", "", "treepm_layout",
     "", "", "  --treepm-layout <auto|linear|gather_linear|gather_morton>\n", "",
     offsetof(SimulationConfig, treePmLayout), 0.0, 0.0, false, false},
    {SimulationOptionGroup::Core, OptionKind::TreePmPrecision, "--treepm-precision", "",
     "treepm_precision", "", "", "  --treepm-precision <fp32|fp64>\n", "",
     offsetof(SimulationConfig, treePmPrecision), 0.0, 0.0, false, false},
    {SimulationOptionGroup::Core, OptionKind::TreePmAssignment, "--treepm-assignment", "",
     "treepm_assignment", "", "", "  --treepm-assignment <cic|tsc|pcs>\n", "",
     offsetof(SimulationConfig, treePmAssignment), 0.0, 0.0, false, false},
    {SimulationOptionGroup::Core, OptionKind::Bool, "--treepm-local-grid", "", "treepm_local_grid",
     "", "", "  --treepm-local-grid <true|false>\n", "",
     offsetof(SimulationConfig, treePmLocalGrid), 0.0, 0.0, false, false},
    {SimulationOptionGroup::Core, OptionKind::Uint, "--treepm-grid-size", "", "treepm_grid_size",
     "", "", "  --treepm-grid-size <32..128>\n", "", offsetof(SimulationConfig, treePmGridSize),
     32.0, 128.0, true, true},
    {SimulationOptionGroup::Core, OptionKind::Uint, "--treepm-jacobi-iters", "",
     "treepm_jacobi_iterations", "", "", "  --treepm-jacobi-iters <4..64>\n", "",
     offsetof(SimulationConfig, treePmJacobiIterations), 4.0, 64.0, true, true},
    {SimulationOptionGroup::Core, OptionKind::Float, "--treepm-cutoff-factor", "",
     "treepm_cutoff_factor", "", "", "  --treepm-cutoff-factor <1..2>\n", "",
     offsetof(SimulationConfig, treePmCutoffFactor), 1.0, 2.0, true, true},
    {SimulationOptionGroup::Core, OptionKind::Uint, "--treepm-max-local-neighbors", "",
     "treepm_max_local_neighbors", "", "", "  --treepm-max-local-neighbors <0..256>\n", "",
     offsetof(SimulationConfig, treePmMaxLocalNeighbors), 0.0, 256.0, true, true},
    {SimulationOptionGroup::Core, OptionKind::Uint, "--treepm-particle-limit", "",
     "treepm_particle_limit", "", "", "  --treepm-particle-limit <0|n>\n", "",
     offsetof(SimulationConfig, treePmParticleLimit), 0.0, 0.0, true, false},
    {SimulationOptionGroup::Core, OptionKind::Uint, "--treepm-dense-cell-threshold", "",
     "treepm_dense_cell_threshold", "", "", "  --treepm-dense-cell-threshold <1..>\n", "",
     offsetof(SimulationConfig, treePmDenseCellThreshold), 1.0, 0.0, true, false},
    {SimulationOptionGroup::Core, OptionKind::Bool, "--treepm-gravity-only-buffers", "",
     "treepm_gravity_only_buffers", "", "", "  --treepm-gravity-only-buffers <true|false>\n", "",
     offsetof(SimulationConfig, treePmGravityOnlyBuffers), 0.0, 0.0, false, false},
    {SimulationOptionGroup::Core, OptionKind::Uint, "--linear-octree-leaf-capacity", "",
     "linear_octree_leaf_capacity", "", "", "  --linear-octree-leaf-capacity <16..>\n", "",
     offsetof(SimulationConfig, linearOctreeLeafCapacity), 16.0, 0.0, true, false},
    {SimulationOptionGroup::Core, OptionKind::String, "--cuda-cache-preference", "",
     "cuda_cache_preference", "", "", "  --cuda-cache-preference <default|l1|shared>\n", "",
     offsetof(SimulationConfig, cudaCachePreference), 0.0, 0.0, false, false},
    {SimulationOptionGroup::Core, OptionKind::ClientParticleCap, "--client-particle-cap", "",
     "client_particle_cap", "", "BLITZAR_CLIENT_DRAW_CAP", "  --client-particle-cap <n>\n", "",
     offsetof(SimulationConfig, clientParticleCap), 0.0, 0.0, false, false},
    {SimulationOptionGroup::Client, OptionKind::Float, "--zoom", "", "default_zoom", "", "",
     "  --zoom <float>\n", "", offsetof(SimulationConfig, defaultZoom), 0.0, 0.0, true, false},
    {SimulationOptionGroup::Client, OptionKind::Int, "--luminosity", "", "default_luminosity", "",
     "", "  --luminosity <0..255>\n", "", offsetof(SimulationConfig, defaultLuminosity),
     kLuminosityMin, kLuminosityMax, true, true},
    {SimulationOptionGroup::Client, OptionKind::String, "--ui-theme", "", "ui_theme", "", "",
     "  --ui-theme <light|dark>\n", "", offsetof(SimulationConfig, uiTheme), 0.0, 0.0, false,
     false},
    {SimulationOptionGroup::Client, OptionKind::Uint, "--ui-fps", "", "ui_fps_limit", "", "",
     "  --ui-fps <n>\n", "", offsetof(SimulationConfig, uiFpsLimit), 1.0, 0.0, true, false},
    {SimulationOptionGroup::Client, OptionKind::TimeoutTriple, "--server-timeout-ms", "",
     "client_remote_timeout_ms", "", "", "  --server-timeout-ms <10..60000>\n", "", 0,
     kRuntimeRemoteTimeoutMinMs, kRuntimeRemoteTimeoutMaxMs, true, true},
    {SimulationOptionGroup::Client, OptionKind::Uint, "--server-command-timeout-ms", "",
     "client_remote_command_timeout_ms", "", "", "  --server-command-timeout-ms <10..60000>\n", "",
     offsetof(SimulationConfig, clientRemoteCommandTimeoutMs), kRuntimeRemoteTimeoutMinMs,
     kRuntimeRemoteTimeoutMaxMs, true, true},
    {SimulationOptionGroup::Client, OptionKind::Uint, "--server-status-timeout-ms", "",
     "client_remote_status_timeout_ms", "", "", "  --server-status-timeout-ms <10..60000>\n", "",
     offsetof(SimulationConfig, clientRemoteStatusTimeoutMs), kRuntimeRemoteTimeoutMinMs,
     kRuntimeRemoteTimeoutMaxMs, true, true},
    {SimulationOptionGroup::Client, OptionKind::Uint, "--server-snapshot-timeout-ms", "",
     "client_remote_snapshot_timeout_ms", "", "", "  --server-snapshot-timeout-ms <10..60000>\n",
     "", offsetof(SimulationConfig, clientRemoteSnapshotTimeoutMs), kRuntimeRemoteTimeoutMinMs,
     kRuntimeRemoteTimeoutMaxMs, true, true},
    {SimulationOptionGroup::Client, OptionKind::Uint, "--snapshot-queue-capacity", "",
     "client_snapshot_queue_capacity", "", "", "  --snapshot-queue-capacity <n>\n", "",
     offsetof(SimulationConfig, clientSnapshotQueueCapacity), 1.0, 64.0, true, true},
    {SimulationOptionGroup::Client, OptionKind::String, "--snapshot-drop-policy", "",
     "client_snapshot_drop_policy", "", "", "  --snapshot-drop-policy <latest-only|paced>\n", "",
     offsetof(SimulationConfig, clientSnapshotDropPolicy), 0.0, 0.0, false, false},
    {SimulationOptionGroup::Client, OptionKind::String, "--export-directory", "",
     "export_directory", "", "", "  --export-directory <path>\n", "",
     offsetof(SimulationConfig, exportDirectory), 0.0, 0.0, false, false},
    {SimulationOptionGroup::Client, OptionKind::String, "--export-format", "", "export_format", "",
     "", "  --export-format <vtk|vtk_binary|xyz|bin>\n", "",
     offsetof(SimulationConfig, exportFormat), 0.0, 0.0, false, false},
    {SimulationOptionGroup::Client, OptionKind::String, "--input-file", "", "input_file", "", "",
     "  --input-file <path>\n", "", offsetof(SimulationConfig, inputFile), 0.0, 0.0, false, false},
    {SimulationOptionGroup::Client, OptionKind::String, "--input-format", "", "input_format", "",
     "", "  --input-format <auto|vtk|vtk_binary|xyz|bin>\n", "",
     offsetof(SimulationConfig, inputFormat), 0.0, 0.0, false, false},
    {SimulationOptionGroup::Client, OptionKind::String, "--init-config-style", "",
     "init_config_style", "", "", "  --init-config-style <preset|detailed>\n", "",
     offsetof(SimulationConfig, initConfigStyle), 0.0, 0.0, false, false},
    {SimulationOptionGroup::Client, OptionKind::String, "--preset-structure", "--structure",
     "preset_structure", "", "",
     "  --preset-structure "
     "<disk_orbit|galaxy|galaxy_collision|cosmology|random_cloud|cube_random|sphere_random|two_"
     "body|three_body|"
     "plummer_sphere|binary_star|solar_system|sph_collapse|file>"
     "\n",
     "  --structure "
     "<disk_orbit|galaxy|galaxy_collision|cosmology|random_cloud|cube_random|sphere_random|two_"
     "body|three_body|"
     "plummer_sphere|binary_star|solar_system|sph_collapse|file> "
     "(alias)\n",
     offsetof(SimulationConfig, presetStructure), 0.0, 0.0, false, false},
    {SimulationOptionGroup::Client, OptionKind::Float, "--preset-size", "--size", "preset_size", "",
     "", "  --preset-size <float>\n", "  --size <float> (alias)\n",
     offsetof(SimulationConfig, presetSize), 0.01, 0.0, true, false},
    {SimulationOptionGroup::Client, OptionKind::Float, "--velocity-temperature", "",
     "velocity_temperature", "temperature", "", "  --velocity-temperature <float>\n", "",
     offsetof(SimulationConfig, velocityTemperature), 0.0, 0.0, true, false},
    {SimulationOptionGroup::Client, OptionKind::Float, "--particle-temperature", "",
     "particle_temperature", "", "", "  --particle-temperature <float>\n", "",
     offsetof(SimulationConfig, particleTemperature), 0.0, 0.0, true, false},
    {SimulationOptionGroup::Client, OptionKind::Float, "--thermal-ambient", "",
     "thermal_ambient_temperature", "", "", "  --thermal-ambient <float>\n", "",
     offsetof(SimulationConfig, thermalAmbientTemperature), 0.0, 0.0, true, false},
    {SimulationOptionGroup::Client, OptionKind::Float, "--thermal-specific-heat", "",
     "thermal_specific_heat", "", "", "  --thermal-specific-heat <float>\n", "",
     offsetof(SimulationConfig, thermalSpecificHeat), 0.000001, 0.0, true, false},
    {SimulationOptionGroup::Client, OptionKind::Float, "--thermal-heating", "",
     "thermal_heating_coeff", "", "", "  --thermal-heating <float>\n", "",
     offsetof(SimulationConfig, thermalHeatingCoeff), 0.0, 0.0, true, false},
    {SimulationOptionGroup::Client, OptionKind::Float, "--thermal-radiation", "",
     "thermal_radiation_coeff", "", "", "  --thermal-radiation <float>\n", "",
     offsetof(SimulationConfig, thermalRadiationCoeff), 0.0, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::String, "--init-mode", "", "init_mode", "", "",
     "  --init-mode "
     "<disk_orbit|galaxy|galaxy_collision|cosmology|random_cloud|cube_random|sphere_random|two_"
     "body|three_body|"
     "plummer_sphere|binary_star|solar_system|sph_collapse|file>"
     "\n",
     "", offsetof(SimulationConfig, initMode), 0.0, 0.0, false, false},
    {SimulationOptionGroup::InitState, OptionKind::Uint, "--init-seed", "", "init_seed", "", "",
     "  --init-seed <n>\n", "", offsetof(SimulationConfig, initSeed), 0.0, 0.0, false, false},
    {SimulationOptionGroup::InitState, OptionKind::Bool, "--init-include-central-body", "",
     "init_include_central_body", "", "", "  --init-include-central-body <true|false>\n", "",
     offsetof(SimulationConfig, initIncludeCentralBody), 0.0, 0.0, false, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-central-mass", "",
     "init_central_mass", "", "", "  --init-central-mass <float>\n", "",
     offsetof(SimulationConfig, initCentralMass), 0.000001, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-central-x", "", "init_central_x",
     "", "", "  --init-central-x <float>\n", "", offsetof(SimulationConfig, initCentralX), 0.0, 0.0,
     false, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-central-y", "", "init_central_y",
     "", "", "  --init-central-y <float>\n", "", offsetof(SimulationConfig, initCentralY), 0.0, 0.0,
     false, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-central-z", "", "init_central_z",
     "", "", "  --init-central-z <float>\n", "", offsetof(SimulationConfig, initCentralZ), 0.0, 0.0,
     false, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-central-vx", "",
     "init_central_vx", "", "", "  --init-central-vx <float>\n", "",
     offsetof(SimulationConfig, initCentralVx), 0.0, 0.0, false, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-central-vy", "",
     "init_central_vy", "", "", "  --init-central-vy <float>\n", "",
     offsetof(SimulationConfig, initCentralVy), 0.0, 0.0, false, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-central-vz", "",
     "init_central_vz", "", "", "  --init-central-vz <float>\n", "",
     offsetof(SimulationConfig, initCentralVz), 0.0, 0.0, false, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-disk-mass", "", "init_disk_mass",
     "", "", "  --init-disk-mass <float>\n", "", offsetof(SimulationConfig, initDiskMass), 0.000001,
     0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-disk-radius-min", "",
     "init_disk_radius_min", "", "", "  --init-disk-radius-min <float>\n", "",
     offsetof(SimulationConfig, initDiskRadiusMin), 0.000001, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-disk-radius-max", "",
     "init_disk_radius_max", "", "", "  --init-disk-radius-max <float>\n", "",
     offsetof(SimulationConfig, initDiskRadiusMax), 0.000001, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-disk-thickness", "",
     "init_disk_thickness", "", "", "  --init-disk-thickness <float>\n", "",
     offsetof(SimulationConfig, initDiskThickness), 0.0, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-velocity-scale", "",
     "init_velocity_scale", "", "", "  --init-velocity-scale <float>\n", "",
     offsetof(SimulationConfig, initVelocityScale), 0.0, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-cloud-half-extent", "",
     "init_cloud_half_extent", "", "", "  --init-cloud-half-extent <float>\n", "",
     offsetof(SimulationConfig, initCloudHalfExtent), 0.000001, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-cube-half-extent", "",
     "init_cube_half_extent", "", "", "  --init-cube-half-extent <float>\n", "",
     offsetof(SimulationConfig, initCubeHalfExtent), 0.000001, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-sphere-radius", "",
     "init_sphere_radius", "", "", "  --init-sphere-radius <float>\n", "",
     offsetof(SimulationConfig, initSphereRadius), 0.000001, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-cloud-speed", "",
     "init_cloud_speed", "", "", "  --init-cloud-speed <float>\n", "",
     offsetof(SimulationConfig, initCloudSpeed), 0.0, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--init-particle-mass", "",
     "init_particle_mass", "", "", "  --init-particle-mass <float>\n", "",
     offsetof(SimulationConfig, initParticleMass), 0.000000000001, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Bool, "--cosmology-enabled", "",
     "cosmology_enabled", "", "", "  --cosmology-enabled <true|false>\n", "",
     offsetof(SimulationConfig, cosmologyEnabled), 0.0, 0.0, false, false},
    {SimulationOptionGroup::InitState, OptionKind::String, "--cosmology-mode", "", "cosmology_mode",
     "", "", "  --cosmology-mode <expanding_preview|comoving>\n", "",
     offsetof(SimulationConfig, cosmologyMode), 0.0, 0.0, false, false},
    {SimulationOptionGroup::InitState, OptionKind::String, "--cosmology-geometry", "",
     "cosmology_geometry", "", "", "  --cosmology-geometry <sphere|cube>\n", "",
     offsetof(SimulationConfig, cosmologyGeometry), 0.0, 0.0, false, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--cosmology-box-half-extent", "",
     "cosmology_box_half_extent", "", "", "  --cosmology-box-half-extent <float>\n", "",
     offsetof(SimulationConfig, cosmologyBoxHalfExtent), 0.000001, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--cosmology-sphere-radius", "",
     "cosmology_sphere_radius", "", "", "  --cosmology-sphere-radius <float>\n", "",
     offsetof(SimulationConfig, cosmologySphereRadius), 0.000001, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--cosmology-h0", "", "cosmology_h0", "",
     "", "  --cosmology-h0 <float>\n", "", offsetof(SimulationConfig, cosmologyHubbleH0), 0.0, 0.0,
     true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--cosmology-omega-m", "",
     "cosmology_omega_m", "", "", "  --cosmology-omega-m <float>\n", "",
     offsetof(SimulationConfig, cosmologyOmegaMatter), 0.0, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--cosmology-omega-lambda", "",
     "cosmology_omega_lambda", "", "", "  --cosmology-omega-lambda <float>\n", "",
     offsetof(SimulationConfig, cosmologyOmegaLambda), 0.0, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--cosmology-omega-radiation", "",
     "cosmology_omega_radiation", "", "", "  --cosmology-omega-radiation <float>\n", "",
     offsetof(SimulationConfig, cosmologyOmegaRadiation), 0.0, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--cosmology-initial-scale-factor", "",
     "cosmology_initial_scale_factor", "", "", "  --cosmology-initial-scale-factor <float>\n", "",
     offsetof(SimulationConfig, cosmologyInitialScaleFactor), 0.000001, 1.0e12, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--cosmology-perturbation", "",
     "cosmology_perturbation_amplitude", "", "", "  --cosmology-perturbation <float>\n", "",
     offsetof(SimulationConfig, cosmologyPerturbationAmplitude), 0.0, 1.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--cosmology-peculiar-velocity", "",
     "cosmology_peculiar_velocity_scale", "", "", "  --cosmology-peculiar-velocity <float>\n", "",
     offsetof(SimulationConfig, cosmologyPeculiarVelocityScale), 0.0, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::String, "--cosmology-mass-model", "",
     "cosmology_mass_model", "", "",
     "  --cosmology-mass-model <critical_density|total_mass|particle_mass>\n", "",
     offsetof(SimulationConfig, cosmologyMassModel), 0.0, 0.0, false, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--cosmology-total-mass", "",
     "cosmology_total_mass", "", "", "  --cosmology-total-mass <float>\n", "",
     offsetof(SimulationConfig, cosmologyTotalMass), 0.0, 0.0, true, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--scene-offset-x", "", "scene_offset_x",
     "", "", "  --scene-offset-x <float>\n", "", offsetof(SimulationConfig, sceneOffsetX), 0.0, 0.0,
     false, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--scene-offset-y", "", "scene_offset_y",
     "", "", "  --scene-offset-y <float>\n", "", offsetof(SimulationConfig, sceneOffsetY), 0.0, 0.0,
     false, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--scene-offset-z", "", "scene_offset_z",
     "", "", "  --scene-offset-z <float>\n", "", offsetof(SimulationConfig, sceneOffsetZ), 0.0, 0.0,
     false, false},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--scene-rotation-x", "",
     "scene_rotation_x", "", "", "  --scene-rotation-x <degrees>\n", "",
     offsetof(SimulationConfig, sceneRotationX), -360.0, 360.0, true, true},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--scene-rotation-y", "",
     "scene_rotation_y", "", "", "  --scene-rotation-y <degrees>\n", "",
     offsetof(SimulationConfig, sceneRotationY), -360.0, 360.0, true, true},
    {SimulationOptionGroup::InitState, OptionKind::Float, "--scene-rotation-z", "",
     "scene_rotation_z", "", "", "  --scene-rotation-z <degrees>\n", "",
     offsetof(SimulationConfig, sceneRotationZ), -360.0, 360.0, true, true},
    {SimulationOptionGroup::InitState, OptionKind::String, "--scene-copy-axis", "",
     "scene_copy_axis", "", "", "  --scene-copy-axis <x|y|z>\n", "",
     offsetof(SimulationConfig, sceneCopyAxis), 0.0, 0.0, false, false},
    {SimulationOptionGroup::InitState, OptionKind::Uint, "--scene-rotation-copies", "",
     "scene_rotation_copies", "", "", "  --scene-rotation-copies <1..256>\n", "",
     offsetof(SimulationConfig, sceneRotationCopies), 1.0, 256.0, true, true},
    {SimulationOptionGroup::InitState, OptionKind::Bool, "--scene-mirror-x", "", "scene_mirror_x",
     "", "", "  --scene-mirror-x <true|false>\n", "", offsetof(SimulationConfig, sceneMirrorX), 0.0,
     0.0, false, false},
    {SimulationOptionGroup::InitState, OptionKind::Bool, "--scene-mirror-y", "", "scene_mirror_y",
     "", "", "  --scene-mirror-y <true|false>\n", "", offsetof(SimulationConfig, sceneMirrorY), 0.0,
     0.0, false, false},
    {SimulationOptionGroup::InitState, OptionKind::Bool, "--scene-mirror-z", "", "scene_mirror_z",
     "", "", "  --scene-mirror-z <true|false>\n", "", offsetof(SimulationConfig, sceneMirrorZ), 0.0,
     0.0, false, false},
    {SimulationOptionGroup::Fluid, OptionKind::Bool, "--sph", "", "sph_enabled", "", "",
     "  --sph <true|false>\n", "", offsetof(SimulationConfig, sphEnabled), 0.0, 0.0, false, false},
    {SimulationOptionGroup::Fluid, OptionKind::Float, "--sph-h", "", "sph_smoothing_length", "", "",
     "  --sph-h <float>\n", "", offsetof(SimulationConfig, sphSmoothingLength), 0.05, 0.0, true,
     false},
    {SimulationOptionGroup::Fluid, OptionKind::Float, "--sph-rest-density", "", "sph_rest_density",
     "", "", "  --sph-rest-density <float>\n", "", offsetof(SimulationConfig, sphRestDensity), 0.01,
     0.0, true, false},
    {SimulationOptionGroup::Fluid, OptionKind::Float, "--sph-gas-constant", "", "sph_gas_constant",
     "", "", "  --sph-gas-constant <float>\n", "", offsetof(SimulationConfig, sphGasConstant), 0.01,
     0.0, true, false},
    {SimulationOptionGroup::Fluid, OptionKind::Float, "--sph-viscosity", "", "sph_viscosity", "",
     "", "  --sph-viscosity <float>\n", "", offsetof(SimulationConfig, sphViscosity), 0.0, 0.0,
     true, false},
    {SimulationOptionGroup::Fluid, OptionKind::Uint, "--energy-every", "",
     "energy_measure_every_steps", "", "", "  --energy-every <n>\n", "",
     offsetof(SimulationConfig, energyMeasureEverySteps), 1.0, 0.0, true, false},
    {SimulationOptionGroup::Fluid, OptionKind::Uint, "--energy-sample-limit", "",
     "energy_sample_limit", "", "", "  --energy-sample-limit <n>\n", "",
     offsetof(SimulationConfig, energySampleLimit), 64.0, 0.0, true, false},
    {SimulationOptionGroup::Core, OptionKind::Bool, "--deterministic", "", "deterministic_mode", "",
     "", "  --deterministic <true|false>\n", "", offsetof(SimulationConfig, deterministicMode), 0.0,
     0.0, false, false},
    {SimulationOptionGroup::Core, OptionKind::Float, "--physics-max-accel", "",
     "physics_max_acceleration", "", "", "  --physics-max-accel <float>\n", "",
     offsetof(SimulationConfig, physicsMaxAcceleration), 0.0, 0.0, true, false},
    {SimulationOptionGroup::Core, OptionKind::Float, "--physics-min-softening", "",
     "physics_min_softening", "", "", "  --physics-min-softening <float>\n", "",
     offsetof(SimulationConfig, physicsMinSoftening), 0.0, 0.0, true, false},
    {SimulationOptionGroup::Core, OptionKind::Float, "--physics-min-dist2", "",
     "physics_min_distance2", "", "", "  --physics-min-dist2 <float>\n", "",
     offsetof(SimulationConfig, physicsMinDistance2), 0.0, 0.0, true, false},
    {SimulationOptionGroup::Core, OptionKind::Float, "--physics-min-theta", "", "physics_min_theta",
     "", "", "  --physics-min-theta <float>\n", "", offsetof(SimulationConfig, physicsMinTheta),
     0.0, 0.0, true, false},
    {SimulationOptionGroup::Fluid, OptionKind::Float, "--sph-max-accel", "", "sph_max_acceleration",
     "", "", "  --sph-max-accel <float>\n", "", offsetof(SimulationConfig, sphMaxAcceleration), 0.0,
     0.0, true, false},
    {SimulationOptionGroup::Fluid, OptionKind::Float, "--sph-max-speed", "", "sph_max_speed", "",
     "", "  --sph-max-speed <float>\n", "", offsetof(SimulationConfig, sphMaxSpeed), 0.0, 0.0, true,
     false},
    {SimulationOptionGroup::Client, OptionKind::Bool, "--render-culling", "",
     "render_culling_enabled", "", "", "  --render-culling <true|false>\n", "",
     offsetof(SimulationConfig, renderCullingEnabled), 0.0, 0.0, false, false},
    {SimulationOptionGroup::Client, OptionKind::Bool, "--render-lod", "", "render_lod_enabled", "",
     "", "  --render-lod <true|false>\n", "", offsetof(SimulationConfig, renderLODEnabled), 0.0,
     0.0, false, false},
    {SimulationOptionGroup::Client, OptionKind::Float, "--render-lod-near", "",
     "render_lod_near_distance", "", "", "  --render-lod-near <float>\n", "",
     offsetof(SimulationConfig, renderLODNearDistance), 0.0, 0.0, true, false},
    {SimulationOptionGroup::Client, OptionKind::Float, "--render-lod-far", "",
     "render_lod_far_distance", "", "", "  --render-lod-far <float>\n", "",
     offsetof(SimulationConfig, renderLODFarDistance), 0.0, 0.0, true, false},
};

const std::size_t kSimulationOptionCount =
    sizeof(kSimulationOptions) / sizeof(kSimulationOptions[0]);

} // namespace bltzr_config
