#ifndef GRAVITY_RUNTIME_INCLUDE_FRONTEND_FRONTENDMODULEHANDLELOAD_HPP_
#define GRAVITY_RUNTIME_INCLUDE_FRONTEND_FRONTENDMODULEHANDLELOAD_HPP_

// Mirror header for FrontendModuleHandleLoad.cpp.
// Load API is declared on FrontendModuleHandle itself.

#endif // GRAVITY_RUNTIME_INCLUDE_FRONTEND_FRONTENDMODULEHANDLELOAD_HPP_
