set(APP_NAME blitzar)
set(HEADLESS_NAME blitzar-headless)
set(SERVER_DAEMON_NAME blitzar-server)
set(CLIENT_HOST_NAME blitzar-client)
set(WEB_GATEWAY_NAME blitzar-web-gateway)
set(CLIENT_MODULE_CLI_NAME gravityClientModuleCli)
set(CLIENT_MODULE_ECHO_NAME gravityClientModuleEcho)
set(CLIENT_MODULE_GUI_PROXY_NAME gravityClientModuleGuiProxy)
set(CLIENT_MODULE_QT_INPROC_NAME gravityClientModuleQtInProc)

option(GRAVITY_BUILD_SERVER_DAEMON "Build dedicated server daemon service" ON)
option(GRAVITY_BUILD_HEADLESS_BINARY "Build headless simulation binary (blitzar-headless)" ON)
option(GRAVITY_BUILD_CLIENT_HOST "Build dynamic client host" ON)
option(GRAVITY_BUILD_WEB_GATEWAY "Build Rust WebSocket/HTTP gateway" ON)
option(GRAVITY_BUILD_CLIENT_MODULES "Build sample dynamic client modules" ON)
option(GRAVITY_BUILD_TESTS "Build deterministic physics regression tests" ON)
option(GRAVITY_PROFILE_LOGS "Print server timings each update" OFF)
option(GRAVITY_STRICT_WARNINGS "Treat project C++ warnings as errors" OFF)
set(GRAVITY_PROFILE "dev" CACHE STRING "Build profile: dev or prod")
set_property(CACHE GRAVITY_PROFILE PROPERTY STRINGS dev prod)
option(
    GRAVITY_SUPPRESS_KNOWN_CUDA_TOOLCHAIN_WARNINGS
    "Suppress known noisy NVCC/EDG warnings from system/third-party headers on Windows toolchains"
    ON
)

string(TOLOWER "${GRAVITY_PROFILE}" GRAVITY_PROFILE)
if(NOT GRAVITY_PROFILE STREQUAL "dev" AND NOT GRAVITY_PROFILE STREQUAL "prod")
    message(FATAL_ERROR "GRAVITY_PROFILE must be one of: dev, prod")
endif()

if(GRAVITY_PROFILE STREQUAL "prod")
    set(GRAVITY_BUILD_CLIENT_HOST OFF CACHE BOOL "Build dynamic client host" FORCE)
    set(GRAVITY_BUILD_CLIENT_MODULES OFF CACHE BOOL "Build sample dynamic client modules" FORCE)
    set(GRAVITY_STRICT_WARNINGS ON CACHE BOOL "Treat project C++ warnings as errors" FORCE)
    set(GRAVITY_PROFILE_LOGS OFF CACHE BOOL "Print server timings each update" FORCE)
    message(STATUS "GRAVITY_PROFILE=prod: dynamic client modules disabled for deterministic critical path")
else()
    message(STATUS "GRAVITY_PROFILE=dev: dynamic client modules allowed")
endif()
