#ifndef GRAVITY_RUNTIME_INCLUDE_CLIENT_CLIENTMODULEHANDLELOAD_HPP_
#define GRAVITY_RUNTIME_INCLUDE_CLIENT_CLIENTMODULEHANDLELOAD_HPP_
// Mirror header for ClientModuleHandleLoad.cpp.
// Load API is declared on ClientModuleHandle itself.
#endif // GRAVITY_RUNTIME_INCLUDE_CLIENT_CLIENTMODULEHANDLELOAD_HPP_
