cmake_minimum_required(VERSION 3.24)

if(NOT DEFINED QT_DIR OR QT_DIR STREQUAL "")
    set(QT_DIR "C:/Qt/6.8.2/msvc2022_64")
endif()
if(NOT DEFINED BUILD_DIR OR BUILD_DIR STREQUAL "")
    set(BUILD_DIR "build")
endif()

message(STATUS "[doctor] cmake version: ${CMAKE_VERSION}")

function(gravity_doctor_program name)
    unset(_prog CACHE)
    unset(_prog)
    find_program(_prog NAMES ${name})
    if(_prog)
        message(STATUS "[doctor] ${name}: ${_prog}")
    else()
        message(WARNING "[doctor] ${name}: not found in PATH")
    endif()
endfunction()

gravity_doctor_program(ninja)
gravity_doctor_program(nvcc)
gravity_doctor_program(cl)

set(_qt_deploy "${QT_DIR}/bin/windeployqt.exe")
if(EXISTS "${_qt_deploy}")
    message(STATUS "[doctor] qt deploy: ${_qt_deploy}")
else()
    message(WARNING "[doctor] qt deploy missing: ${_qt_deploy}")
endif()

set(_module_host "${BUILD_DIR}/myAppModuleHost.exe")
if(EXISTS "${_module_host}")
    message(STATUS "[doctor] module host: ${_module_host}")
else()
    message(WARNING "[doctor] module host missing: ${_module_host}")
endif()

set(_qt_module "${BUILD_DIR}/gravityFrontendModuleQtInProc.dll")
if(EXISTS "${_qt_module}")
    message(STATUS "[doctor] qt module: ${_qt_module}")
else()
    message(WARNING "[doctor] qt module missing: ${_qt_module}")
endif()
