# @file engine/config/Module.cmake
# @brief Configuration responsibility aggregator.

include("${CMAKE_CURRENT_LIST_DIR}/args/Module.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/core/Module.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/directive/Module.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/env/Module.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/modes/Module.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/profile/Module.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/registry/Module.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/text/Module.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/validation/Module.cmake")

set(BLITZAR_CONFIG_INCLUDE_DIR "${BLITZAR_ROOT_DIR}/engine/config/include")
set(BLITZAR_CONFIG_INCLUDE_DIRS
    ${BLITZAR_CONFIG_INCLUDE_DIR}
    ${BLITZAR_CONFIG_ARGS_INCLUDE_DIR}
    ${BLITZAR_CONFIG_CORE_INCLUDE_DIR}
    ${BLITZAR_CONFIG_DIRECTIVE_INCLUDE_DIR}
    ${BLITZAR_CONFIG_ENV_INCLUDE_DIR}
    ${BLITZAR_CONFIG_MODES_INCLUDE_DIR}
    ${BLITZAR_CONFIG_PROFILE_INCLUDE_DIR}
    ${BLITZAR_CONFIG_REGISTRY_INCLUDE_DIR}
    ${BLITZAR_CONFIG_TEXT_INCLUDE_DIR}
    ${BLITZAR_CONFIG_VALIDATION_INCLUDE_DIR}
)
set(BLITZAR_CONFIG_SOURCE_DIRS
    ${BLITZAR_CONFIG_ARGS_SOURCE_DIR}
    ${BLITZAR_CONFIG_CORE_SOURCE_DIR}
    ${BLITZAR_CONFIG_DIRECTIVE_SOURCE_DIR}
    ${BLITZAR_CONFIG_ENV_SOURCE_DIR}
    ${BLITZAR_CONFIG_MODES_SOURCE_DIR}
    ${BLITZAR_CONFIG_PROFILE_SOURCE_DIR}
    ${BLITZAR_CONFIG_REGISTRY_SOURCE_DIR}
    ${BLITZAR_CONFIG_TEXT_SOURCE_DIR}
    ${BLITZAR_CONFIG_VALIDATION_SOURCE_DIR}
)
set(BLITZAR_CONFIG_ENV_SOURCE ${BLITZAR_CONFIG_ENV_SOURCES})
set(BLITZAR_CONFIG_SOURCES
    ${BLITZAR_CONFIG_ARGS_SOURCES}
    ${BLITZAR_CONFIG_CORE_SOURCES}
    ${BLITZAR_CONFIG_DIRECTIVE_SOURCES}
    ${BLITZAR_CONFIG_ENV_SOURCES}
    ${BLITZAR_CONFIG_MODES_SOURCES}
    ${BLITZAR_CONFIG_PROFILE_SOURCES}
    ${BLITZAR_CONFIG_REGISTRY_SOURCES}
    ${BLITZAR_CONFIG_TEXT_SOURCES}
    ${BLITZAR_CONFIG_VALIDATION_SOURCES}
)
set(BLITZAR_CONFIG_COMMAND_SOURCES
    ${BLITZAR_CONFIG_ARGS_COMMAND_SOURCES}
    ${BLITZAR_CONFIG_CORE_SOURCES}
    ${BLITZAR_CONFIG_DIRECTIVE_SOURCES}
    ${BLITZAR_CONFIG_MODES_SOURCES}
    ${BLITZAR_CONFIG_PROFILE_COMMAND_SOURCES}
    ${BLITZAR_CONFIG_REGISTRY_SOURCES}
    ${BLITZAR_CONFIG_TEXT_SOURCES}
    ${BLITZAR_CONFIG_VALIDATION_SOURCES}
)
