set(BLITZAR_INSTALL_CMAKEDIR
    ${CMAKE_INSTALL_LIBDIR}/cmake/BLITZAR)

install(TARGETS blitzar
    EXPORT BLITZARTargets
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
    INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
)
install(FILES
    include/blitzar/blitzar.h
    include/blitzar/blitzar.hpp
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/blitzar
)

configure_package_config_file(
    cmake/blitzar_config.cmake.in
    ${CMAKE_CURRENT_BINARY_DIR}/BLITZARConfig.cmake
    INSTALL_DESTINATION ${BLITZAR_INSTALL_CMAKEDIR}
)
write_basic_package_version_file(
    ${CMAKE_CURRENT_BINARY_DIR}/BLITZARConfigVersion.cmake
    COMPATIBILITY SameMajorVersion
)
install(EXPORT BLITZARTargets
    FILE BLITZARTargets.cmake
    NAMESPACE BLITZAR::
    DESTINATION ${BLITZAR_INSTALL_CMAKEDIR}
)
install(FILES
    ${CMAKE_CURRENT_BINARY_DIR}/BLITZARConfig.cmake
    ${CMAKE_CURRENT_BINARY_DIR}/BLITZARConfigVersion.cmake
    DESTINATION ${BLITZAR_INSTALL_CMAKEDIR}
)
