# @file cmake/win.cmake
# @author Luis1454
# @project BLITZAR
# @brief CMake build orchestration for BLITZAR targets and tooling.

option(
    GRAVITY_WINDOWS_AUTODETECT_TOOLCHAIN
    "Autodetect MSVC/Windows SDK paths and mutate PATH/INCLUDE/LIB during configure (Windows only)"
    ON
)

if(NOT DEFINED CMAKE_TOOLCHAIN_FILE)
    if(DEFINED ENV{VCPKG_ROOT} AND EXISTS "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake")
        set(CMAKE_TOOLCHAIN_FILE "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake" CACHE FILEPATH "vcpkg toolchain file")
    elseif(DEFINED ENV{VCPKG_INSTALLATION_ROOT} AND EXISTS "$ENV{VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake")
        set(CMAKE_TOOLCHAIN_FILE "$ENV{VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake" CACHE FILEPATH "vcpkg toolchain file")
    elseif(EXISTS "$ENV{SystemDrive}/vcpkg/scripts/buildsystems/vcpkg.cmake")
        set(CMAKE_TOOLCHAIN_FILE "$ENV{SystemDrive}/vcpkg/scripts/buildsystems/vcpkg.cmake" CACHE FILEPATH "vcpkg toolchain file")
    endif()
endif()

if(WIN32)
    set(VCPKG_APPLOCAL_DEPS OFF)
    set(PF86 "$ENV{SystemDrive}/Program Files (x86)")
endif()

if(WIN32 AND GRAVITY_WINDOWS_AUTODETECT_TOOLCHAIN)
    file(GLOB _msvc_roots "${PF86}/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/*")
    if(_msvc_roots)
        list(SORT _msvc_roots COMPARE NATURAL ORDER DESCENDING)
        list(GET _msvc_roots 0 _msvc_root)
        set(_msvc_host_bin "${_msvc_root}/bin/Hostx64/x64")
        set(GRAVITY_MSVC_LIB_DIR "${_msvc_root}/lib/x64")
        set(GRAVITY_MSVC_INCLUDE_DIR "${_msvc_root}/include")
        set(ENV{PATH} "${_msvc_host_bin};$ENV{PATH}")
        if(EXISTS "${_msvc_host_bin}/cl.exe" AND NOT DEFINED CMAKE_CUDA_HOST_COMPILER)
            set(CMAKE_CUDA_HOST_COMPILER "${_msvc_host_bin}/cl.exe" CACHE FILEPATH "MSVC host compiler for nvcc" FORCE)
        endif()
        if(EXISTS "${_msvc_root}/include")
            set(ENV{INCLUDE} "${_msvc_root}/include;$ENV{INCLUDE}")
        endif()
        if(EXISTS "${_msvc_root}/lib/x64")
            set(ENV{LIB} "${_msvc_root}/lib/x64;$ENV{LIB}")
            set(ENV{LIBPATH} "${_msvc_root}/lib/x64;$ENV{LIBPATH}")
        endif()
    endif()

    file(GLOB _winsdk_x64_bins "${PF86}/Windows Kits/10/bin/*/x64")
    if(_winsdk_x64_bins)
        list(SORT _winsdk_x64_bins COMPARE NATURAL ORDER DESCENDING)
        list(GET _winsdk_x64_bins 0 _winsdk_x64_bin)
        set(ENV{PATH} "${_winsdk_x64_bin};$ENV{PATH}")
        if(EXISTS "${_winsdk_x64_bin}/rc.exe" AND NOT DEFINED CMAKE_RC_COMPILER)
            set(CMAKE_RC_COMPILER "${_winsdk_x64_bin}/rc.exe" CACHE FILEPATH "Windows SDK resource compiler" FORCE)
        endif()
        if(EXISTS "${_winsdk_x64_bin}/mt.exe" AND NOT DEFINED CMAKE_MT)
            set(CMAKE_MT "${_winsdk_x64_bin}/mt.exe" CACHE FILEPATH "Windows SDK manifest tool" FORCE)
        endif()
    endif()

    file(GLOB _winsdk_include_versions "${PF86}/Windows Kits/10/Include/*")
    if(_winsdk_include_versions)
        list(SORT _winsdk_include_versions COMPARE NATURAL ORDER DESCENDING)
        list(GET _winsdk_include_versions 0 _winsdk_include_root)
        set(GRAVITY_WINSDK_INCLUDE_UCRT "${_winsdk_include_root}/ucrt")
        set(GRAVITY_WINSDK_INCLUDE_UM "${_winsdk_include_root}/um")
        set(GRAVITY_WINSDK_INCLUDE_SHARED "${_winsdk_include_root}/shared")
        set(GRAVITY_WINSDK_INCLUDE_WINRT "${_winsdk_include_root}/winrt")
        set(GRAVITY_WINSDK_INCLUDE_CPPWINRT "${_winsdk_include_root}/cppwinrt")
        set(ENV{INCLUDE} "${_winsdk_include_root}/ucrt;${_winsdk_include_root}/um;${_winsdk_include_root}/shared;${_winsdk_include_root}/winrt;${_winsdk_include_root}/cppwinrt;$ENV{INCLUDE}")
    endif()

    file(GLOB _winsdk_lib_versions "${PF86}/Windows Kits/10/Lib/*")
    if(_winsdk_lib_versions)
        list(SORT _winsdk_lib_versions COMPARE NATURAL ORDER DESCENDING)
        list(GET _winsdk_lib_versions 0 _winsdk_lib_root)
        set(GRAVITY_WINSDK_UCRT_LIB_DIR "${_winsdk_lib_root}/ucrt/x64")
        set(GRAVITY_WINSDK_UM_LIB_DIR "${_winsdk_lib_root}/um/x64")
        set(ENV{LIB} "${_winsdk_lib_root}/ucrt/x64;${_winsdk_lib_root}/um/x64;$ENV{LIB}")
        set(ENV{LIBPATH} "${_winsdk_lib_root}/ucrt/x64;${_winsdk_lib_root}/um/x64;$ENV{LIBPATH}")
    endif()
endif()

function(gravity_populate_windows_toolchain_hints)
    if(NOT WIN32)
        return()
    endif()

    if((NOT DEFINED GRAVITY_MSVC_INCLUDE_DIR OR NOT EXISTS "${GRAVITY_MSVC_INCLUDE_DIR}")
       OR (NOT DEFINED GRAVITY_MSVC_LIB_DIR OR NOT EXISTS "${GRAVITY_MSVC_LIB_DIR}"))
        if(DEFINED CMAKE_CXX_COMPILER AND EXISTS "${CMAKE_CXX_COMPILER}")
            get_filename_component(_gravity_cxx_compiler_dir "${CMAKE_CXX_COMPILER}" DIRECTORY)
            get_filename_component(_gravity_msvc_host_dir "${_gravity_cxx_compiler_dir}" DIRECTORY)
            get_filename_component(_gravity_msvc_bin_dir "${_gravity_msvc_host_dir}" DIRECTORY)
            get_filename_component(_gravity_msvc_root "${_gravity_msvc_bin_dir}" DIRECTORY)
            if(EXISTS "${_gravity_msvc_root}/include")
                set(GRAVITY_MSVC_INCLUDE_DIR "${_gravity_msvc_root}/include" CACHE PATH "MSVC include directory" FORCE)
            endif()
            if(EXISTS "${_gravity_msvc_root}/lib/x64")
                set(GRAVITY_MSVC_LIB_DIR "${_gravity_msvc_root}/lib/x64" CACHE PATH "MSVC x64 library directory" FORCE)
            endif()
        endif()
    endif()

    if((NOT DEFINED GRAVITY_WINSDK_INCLUDE_UCRT OR NOT EXISTS "${GRAVITY_WINSDK_INCLUDE_UCRT}")
       OR (NOT DEFINED GRAVITY_WINSDK_UM_LIB_DIR OR NOT EXISTS "${GRAVITY_WINSDK_UM_LIB_DIR}"))
        file(GLOB _gravity_winsdk_include_versions "${PF86}/Windows Kits/10/Include/*")
        if(_gravity_winsdk_include_versions)
            list(SORT _gravity_winsdk_include_versions COMPARE NATURAL ORDER DESCENDING)
            list(GET _gravity_winsdk_include_versions 0 _gravity_winsdk_include_root)
            if(EXISTS "${_gravity_winsdk_include_root}/ucrt")
                set(GRAVITY_WINSDK_INCLUDE_UCRT "${_gravity_winsdk_include_root}/ucrt" CACHE PATH "Windows SDK UCRT include dir" FORCE)
            endif()
            if(EXISTS "${_gravity_winsdk_include_root}/um")
                set(GRAVITY_WINSDK_INCLUDE_UM "${_gravity_winsdk_include_root}/um" CACHE PATH "Windows SDK UM include dir" FORCE)
            endif()
            if(EXISTS "${_gravity_winsdk_include_root}/shared")
                set(GRAVITY_WINSDK_INCLUDE_SHARED "${_gravity_winsdk_include_root}/shared" CACHE PATH "Windows SDK shared include dir" FORCE)
            endif()
            if(EXISTS "${_gravity_winsdk_include_root}/winrt")
                set(GRAVITY_WINSDK_INCLUDE_WINRT "${_gravity_winsdk_include_root}/winrt" CACHE PATH "Windows SDK WinRT include dir" FORCE)
            endif()
            if(EXISTS "${_gravity_winsdk_include_root}/cppwinrt")
                set(GRAVITY_WINSDK_INCLUDE_CPPWINRT "${_gravity_winsdk_include_root}/cppwinrt" CACHE PATH "Windows SDK C++/WinRT include dir" FORCE)
            endif()
        endif()

        file(GLOB _gravity_winsdk_lib_versions "${PF86}/Windows Kits/10/Lib/*")
        if(_gravity_winsdk_lib_versions)
            list(SORT _gravity_winsdk_lib_versions COMPARE NATURAL ORDER DESCENDING)
            list(GET _gravity_winsdk_lib_versions 0 _gravity_winsdk_lib_root)
            if(EXISTS "${_gravity_winsdk_lib_root}/ucrt/x64")
                set(GRAVITY_WINSDK_UCRT_LIB_DIR "${_gravity_winsdk_lib_root}/ucrt/x64" CACHE PATH "Windows SDK UCRT x64 lib dir" FORCE)
            endif()
            if(EXISTS "${_gravity_winsdk_lib_root}/um/x64")
                set(GRAVITY_WINSDK_UM_LIB_DIR "${_gravity_winsdk_lib_root}/um/x64" CACHE PATH "Windows SDK UM x64 lib dir" FORCE)
            endif()
        endif()
    endif()

    if(MSVC AND (NOT DEFINED GRAVITY_MSVC_INCLUDE_DIR OR NOT EXISTS "${GRAVITY_MSVC_INCLUDE_DIR}"))
        message(FATAL_ERROR
            "MSVC standard include directory could not be resolved. "
            "Set GRAVITY_MSVC_INCLUDE_DIR manually or run configure from a VS Developer prompt.")
    endif()
endfunction()
